name: CI

on:
  pull_request:
    branches: [master]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
      - run: yarn typechain
      - run: yarn build
      - run: yarn typecheck

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/yarn
      - run: yarn typechain
      - run: yarn build
      - run: yarn lint:ci
